### ISSUE TITLE
Collapsing imports prevents toggling with no selection

### ISSUE THREAD

**Issue by Saucistophe** [Noorts/Toggler#4]
Hi there, I have a strange one.
Clicking on a part of a togglable word is usually enough to trigger a partial match. However, this does not work on my java _files_. It does work on _scratch_ file with exactly the same data. What's even stranger, it works when selecting the exact part that I want to toggle.

![toggler](https://user-images.githubusercontent.com/7082839/127843197-3c4085b4-8e17-4290-ad5e-7f6721cd3fce.gif)

I can reproduce on at least 3 of our repos (Those use Maven, Spring web, Lombok, and mapstruct).
I run IntelliJ Idea 2021.2, with the following extensions:
![image](https://user-images.githubusercontent.com/7082839/127843538-7ee17254-b281-4021-9b17-c9c01be2c79a.png)

Also, I absolutely love this extension. Thank you.

**Comment by Saucistophe** [comment]
After building the plugin and adding logs, I found the culprit. It's due to the collapsed import section! When it's collapsed, the amount of lines hidden from the editor is not counted somehow, and the line is off.

![toggler_aha](https://user-images.githubusercontent.com/7082839/127849548-04ebfaab-55b5-452f-b1ff-7014c99af425.gif)

**Comment by Noorts** [comment]
Hey @Saucistophe!

Thanks for letting me know about the issue and for the subsequent investigation as to what the culprit is. I definitely appreciate it 👍.

I'll look into a solution soon and let you know once I know more.

**Comment by Saucistophe** [comment]
Thanks!
I tried implementing a unit test to reproduce it, but I cannot wrap my head around those IntelliJ fixtures.

Let me know if you need any help or input.

**Comment by Noorts** [comment]
Hey @Saucistophe,

The issue should be resolved as per [commit](https://github.com/Noorts/Toggler/commit/9e33df40cdfdfb4e2b894fae4be9cacd474d0a8f). It was a relatively small fix. A `LogicalPosition` (unfolded) is now used instead of a `VisualPosition` (folded). The text replacement API expects an unfolded position so this small change fixes the problem that folding caused.

Once again thanks for the report 👍. If you run into any other problems, do let me know, so that we can take care of them 😄. 

The new update (v1.2.2) is available [here](https://github.com/Noorts/Toggler/releases) as a release and will be available on the marketplace and in your IDE once JetBrains approves the update (usually two business days).

**Comment by Saucistophe** [comment]
Thank you for the explanation and the quick fix!

**Comment by Saucistophe** [comment]
It's deployed, and it works!
